#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Medallion Architecture: Raw to Bronze Level

    This module ingests raw Synapse data generated by the Synapse Snowflake 
    annotation scraping job running on Google Cloud Run. It transforms these 
    raw annotations into aggregated manifest tables, constructs the ID provenance 
    table to capture file–biospecimen relationships, and builds supporting indexing 
    tables. All outputs are promoted into the bronze layer of the medallion
    architecture by uploading to BigQuery in the htan2-dcc project.

Configurations:

    This module reads configuration settings from
    'configs/config.json' and 'configs/schema.json'
    for Synapse and BigQuery data retrieval.

Functions:
    - main()
    
Authors:      Dar'ya Pozhidayeva <dpozhida@systemsbiology.org>,
              Clarisse Lau <clau@systemsbiology.org>
Date Created: 08-20-2025
Date Updated: 10-15-2025
Modified By:  Yamina Katariya <ykatariy@systemsbiology.org>
"""
import json
import pandas as pd
import synapseclient as sc

from workflow_functions.client_load import (
    load_bq,
    init_bq_client,
    init_synapse_client,
)

from utils.data_utils import (
    flatten_annotation_list,
    sanitize_bq_name
)


# -----------------------
# BQ Destinations
# -----------------------
HTAN_BQ_PROJECT = "htan2-dcc"
MEDALLION_LAYER = "htan2_medallion_bronze"

def main():
    """Process and load Synapse + HTAN2 data into BigQuery."""

    # Initialize clients
    syn = init_synapse_client()
    client = init_bq_client()

    # Build per-component Manifest tables from synapse_raw annotations
    all_annotations = client.query(f"""
        SELECT * 
        FROM `{HTAN_BQ_PROJECT}.synapse_raw.synape_annotations_dyp`
    """).result().to_dataframe()

    components = sorted(all_annotations["component"].dropna().unique())
    #Pull in BQ Hashing Table
    bq_hash_table = client.query("""SELECT project_id, entity_id, name, value, BQ_hash FROM `htan2-dcc.synapse_raw.bq_hash_minting_table`""").result().to_dataframe()
    bq_hash_table = bq_hash_table.rename(columns={"value": "HTAN_Data_File_ID"})
    # Generating combined assay tables
    print("\nGenerating Combined Assay Tables...\n")
    for component in components:
        table_name = f"bronze_METADATA_TABLE_Manifest_{component}"

        comp_annots = all_annotations[all_annotations["component"] == component]
        df_expanded = comp_annots["annotations"].apply(flatten_annotation_list).apply(pd.Series)
        combined_assay_table = pd.concat([comp_annots.drop(columns="annotations"),df_expanded],
                                         axis=1)
        combined_assay_table = combined_assay_table.drop(columns=["component"],
                                                         errors="ignore")
        #Apply BQ Hashing based on entity ID and HTAN Data File ID
        combined_assay_table = pd.merge(combined_assay_table, bq_hash_table,on=["entity_id", "HTAN_Data_File_ID"],how="inner")

        # Create BigQuery table schema (STRING by default; File_Size/Manifest_Version as integer)
        bq_schema = []
        for column_name, _ in combined_assay_table.dtypes.items():
            bq_schema.append({
                "name": sanitize_bq_name(column_name),
                "type": "STRING" if column_name not in ["File_Size",
                                                        "Manifest_Version"] else "integer",
            })

        # Make column names BigQuery-friendly
        combined_assay_table.columns = combined_assay_table.columns.str \
            .replace(r"[^0-9a-zA-Z]+","_", regex=True)

        print("\n Processing:", table_name, "\n")

        load_bq(
            client,
            HTAN_BQ_PROJECT,
            MEDALLION_LAYER,
            table_name,
            combined_assay_table,
        )

        # Pull & group selected Synapse tables (Demographics, Biospecimen)
        all_tables = syn.tableQuery("SELECT * FROM syn68830580").asDataFrame()

        # WILL NEED TO BE UPDATED ONCE REAL DATA IS SUBMITTED!!!
        include_list = ["Demographics", "Biospecimen"]

        filtered_tables = all_tables[all_tables["name"].str.contains(
            "|".join(include_list),
            na=False)]
        grouped = filtered_tables.groupby(["name"])["id"].apply(list)

        grouped_dataframes: dict[str, pd.DataFrame] = {}

        for name, table_ids in grouped.items():
            all_dfs = []
            for table_id in table_ids:
                try:
                    df = syn.tableQuery(f"SELECT * FROM {table_id}").asDataFrame()
                    df["source_table"] = table_id  # track origin (optional)
                    all_dfs.append(df)
                except sc.SynapseNotFoundError as e:
                    print(f"Failed to fetch table {table_id}: {e}")
            if all_dfs:
                grouped_dataframes[name] = pd.concat(all_dfs, ignore_index=True)

        # Upload grouped dataframes to BigQuery
        for name, df in grouped_dataframes.items():
            out_table = f"bronze_METADATA_TABLE_Manifest_{name.replace(' ', '_').replace('-', '_')}"
            load_bq(
                client,
                HTAN_BQ_PROJECT,
                MEDALLION_LAYER,
                out_table,
                df,
            )

    # File ancestry walker → upstream IDs table
    bios = client.query(f"""
        SELECT * FROM `{HTAN_BQ_PROJECT}.{MEDALLION_LAYER}.bronze_LINKING_VIEW_Biospecimen`
    """).result().to_dataframe()

    table_list = client.list_tables(f"{HTAN_BQ_PROJECT}.{MEDALLION_LAYER}")

    all_columns = client.query(f"""
        SELECT table_name, column_name
        FROM `{HTAN_BQ_PROJECT}.{MEDALLION_LAYER}.INFORMATION_SCHEMA.COLUMNS`
    """).result().to_dataframe()

    f = pd.DataFrame()
    for t in table_list:
        tn = t.table_id
        if tn not in ["OtherAssay", "ExSeqMinimal"] and "Auxiliary" not in tn and "Level" not in tn:
            continue

        print("\n Processing:", tn, "\n")

        cols = list(all_columns[all_columns["table_name"] == tn]["column_name"])

        common_cols = [
            "HTAN_Data_File_ID",
            "Filename",
            "entity_id",
            "Component",
            "project_name",
        ]
        if "HTAN_Parent_Biospecimen_ID" in cols:
            common_cols.append("HTAN_Parent_Biospecimen_ID")
        if "HTAN_Parent_Data_File_ID" in cols:
            common_cols.append("HTAN_Parent_Data_File_ID")

        df = client.query(f"""
            SELECT {", ".join(common_cols)}
            FROM `{t.project}.{t.dataset_id}.{t.table_id}`
        """).result().to_dataframe()

        f = pd.concat([f, df], ignore_index=True)

    # Expand comma/semicolon-separated parent lists into individual rows
    f = f.assign(HTAN_Parent_Data_File_ID=f.HTAN_Parent_Data_File_ID.str \
                 .split("[,;]")).explode("HTAN_Parent_Data_File_ID")
    f = f.assign(HTAN_Parent_Biospecimen_ID=f.HTAN_Parent_Biospecimen_ID.str \
                 .split("[,;]")).explode("HTAN_Parent_Biospecimen_ID")
    f = f.applymap(lambda x: x.strip() if isinstance(x, str) else x).drop_duplicates()

    print("\nGenerating Upstream and Linking Tables...\n")

    # Self-joins to walk parent → grandparent → great-grandparent
    f = (
        f.merge(
            f[["HTAN_Data_File_ID", "HTAN_Parent_Data_File_ID"]],
            left_on="HTAN_Parent_Data_File_ID",
            right_on="HTAN_Data_File_ID",
            how="left",
        )
        .drop_duplicates()
        .rename(columns={
            "HTAN_Parent_Data_File_ID_y": "gParent_File_ID",
            "HTAN_Parent_Data_File_ID_x": "HTAN_Parent_Data_File_ID",
            "HTAN_Data_File_ID_x": "HTAN_Data_File_ID",
        })
        .drop(columns="HTAN_Data_File_ID_y")
        .merge(
            f[["HTAN_Data_File_ID", "HTAN_Parent_Data_File_ID"]],
            left_on="gParent_File_ID",
            right_on="HTAN_Data_File_ID",
            how="left",
        )
        .drop_duplicates()
        .rename(columns={
            "HTAN_Data_File_ID_x": "HTAN_Data_File_ID",
            "HTAN_Parent_Data_File_ID_y": "ggParent_File_ID",
            "HTAN_Parent_Data_File_ID_x": "HTAN_Parent_Data_File_ID",
        })
        .drop(columns="HTAN_Data_File_ID_y")
    )

    # Coalesce 'highest' level parent data file
    f["coalesce"] = f[["ggParent_File_ID",
                       "gParent_File_ID",
                       "HTAN_Parent_Data_File_ID"]].bfill(axis=1).iloc[:, 0]

    # Map highest-available ancestor to its biospecimen
    f = (
        f.merge(
            f[["HTAN_Data_File_ID", "HTAN_Parent_Biospecimen_ID"]],
            left_on="coalesce",
            right_on="HTAN_Data_File_ID",
            how="left",
        )
        .drop_duplicates()
        .assign(HTAN_Parent_Biospecimen_ID_x=lambda x: x["HTAN_Parent_Biospecimen_ID_x"] \
                .fillna(x["HTAN_Parent_Biospecimen_ID_y"]))
        .rename(columns={
            "HTAN_Data_File_ID_x": "HTAN_Data_File_ID",
            "HTAN_Parent_Biospecimen_ID_x": "HTAN_Assayed_Biospecimen_ID",
        })
        .drop(columns=[
            "HTAN_Data_File_ID_y",
            "gParent_File_ID",
            "coalesce",
            "HTAN_Parent_Biospecimen_ID_y",
            "ggParent_File_ID",
        ])
    )

    # Join file table with biospecimen walker table
    id_prov = (
        f.merge(bios, on="HTAN_Assayed_Biospecimen_ID", how="left")
         .drop_duplicates()
         .rename(columns={"fileEntityId": "entity_id"})
    )

    # Load upstream IDs
    load_bq(
        client,
        HTAN_BQ_PROJECT,
        MEDALLION_LAYER,
        "bronze_INDEXING_TABLE_Upstream_IDs",
        id_prov,
        json.load(open("configs/schema.json")),
    )

    # Unique IDs (Datafile / Participant)
    unique_ids_minted_datafiles = (
        id_prov[["entity_id", "HTAN_Data_File_ID", "project_name"]]
        .drop_duplicates("HTAN_Data_File_ID")
        .dropna()
    )
    unique_ids_minted_patients = (
        id_prov[["entity_id", "HTAN_Participant_ID", "project_name"]]
        .drop_duplicates("HTAN_Participant_ID")
        .dropna()
    )
    load_bq(
        client,
        HTAN_BQ_PROJECT,
        MEDALLION_LAYER,
        "bronze_INDEXING_TABLE_Minted_Datafile_IDs",
        unique_ids_minted_datafiles,
    )
    load_bq(
        client,
        HTAN_BQ_PROJECT,
        MEDALLION_LAYER,
        "bronze_INDEXING_TABLE_Minted_Participant_IDs",
        unique_ids_minted_patients,
    )



if __name__ == "__main__":
    main()
