#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Medallion Architecture: Raw to Bronze Level

    This module ingests raw Synapse data generated by the Synapse Snowflake 
    annotation scraping job running on Google Cloud Run. It transforms these 
    raw annotations into aggregated manifest tables, constructs the ID provenance 
    table to capture file–biospecimen relationships, and builds supporting indexing tables. 
    All outputs are promoted into the bronze layer of the medallion architecture by uploading to 
    BigQuery in the htan2-dcc project.

Configurations:

    This module reads configuration settings from
    'configs/config.json' and 'configs/schema.json'
    for Synapse and BigQuery data retrieval.
    
    To run this script, you must have valid Synapse credentials (username and API key or personal access token) 
    available in your environment so the Synapse client can authenticate. In addition, the script requires Google 
    Cloud credentials with permission to read and write BigQuery tables in the htan2-dcc project. These are typically 
    provided by setting the GOOGLE_APPLICATION_CREDENTIALS environment variable to point to a service account key JSON. 
    Without both sets of credentials, the script cannot access the raw Synapse data or upload the processed results to BigQuery.

Functions:
    - main()
    
Author:       Dar'ya Pozhidayeva <dpozhida@systemsbiology.org>, Clarisse Lau 
Date Created: 8-20-2025
Date Updated: 8-20-2025
"""
import json
import regex as re
import pandas as pd

from workflow_functions.client_load import (
    load_bq,
    init_bq_client,
    init_synapse_client,
)

# -----------------------
# BQ Destinations
# -----------------------
htan_bq_project = "htan2-dcc"
medallion_layer = "htan2_medallion_bronze"

# -----------------------
# Helper Functions
# -----------------------

def flatten_annotation_list(lst):
    """
    Flatten a list of dicts with 'key' and 'value' into a flat dict.
    If 'value' is array-like, take the first element.
    """
    out = {}
    for item in lst:
        if isinstance(item, dict) and "key" in item and "value" in item:
            val = item["value"]
            out[item["key"]] = val[0] if hasattr(val, "__getitem__") else val
    return out


def sanitize_bq_name(name: str) -> str:
    """BigQuery-friendly column/table token (letters/digits/underscore)."""
    return re.sub(r"[^0-9a-zA-Z]+", "_", name)


def select_existing_columns(df: pd.DataFrame, cols: list[str]) -> list[str]:
    """Return list of columns that exist in df (preserves order)."""
    return [c for c in cols if c in df.columns]


# -----------------------
# Main
# -----------------------

def main():
    """Process and load Synapse + HTAN2 data into BigQuery."""
    # Initialize clients
    syn = init_synapse_client()
    client = init_bq_client()

    # -----------------------
    # Build per-component Manifest tables from synapse_raw annotations
    # -----------------------
    all_annotations = client.query("""
        SELECT * FROM `htan2-dcc.synapse_raw.synape_annotations_dyp`
    """).result().to_dataframe()

    components = sorted(all_annotations["component"].dropna().unique())

    for component in components:
        table_name = f"bronze_METADATA_TABLE_Manifest_{component}"

        comp_annots = all_annotations[all_annotations["component"] == component]
        df_expanded = comp_annots["annotations"].apply(flatten_annotation_list).apply(pd.Series)
        combined_assay_table = pd.concat([comp_annots.drop(columns="annotations"), df_expanded], axis=1)
        combined_assay_table = combined_assay_table.drop(columns=["component"], errors="ignore")

        # Create BigQuery table schema (STRING by default; File_Size/Manifest_Version as integer)
        bq_schema = []
        for column_name, _dtype in combined_assay_table.dtypes.items():
            bq_schema.append({
                "name": sanitize_bq_name(column_name),
                "type": "STRING" if column_name not in ["File_Size", "Manifest_Version"] else "integer",
            })

        # Make column names BigQuery-friendly
        combined_assay_table.columns = combined_assay_table.columns.str.replace(r"[^0-9a-zA-Z]+", "_", regex=True)

        load_bq(
            client,
            htan_bq_project,
            medallion_layer,
            table_name,
            combined_assay_table,
        )

        # -----------------------
        # Pull & group selected Synapse tables (Demographics, Biospecimen)
        # -----------------------
        query = "SELECT * FROM syn68830580"
        all_tables = syn.tableQuery(query).asDataFrame()

        include_list = ["Demographics", "Biospecimen"] #Will likely need to be updated once real data is created. #Name matching is an assumption.
        pattern = "|".join(include_list)

        filtered_tables = all_tables[all_tables["name"].str.contains(pattern, na=False)]
        grouped = filtered_tables.groupby(["name"])["id"].apply(list)

        grouped_dataframes: dict[str, pd.DataFrame] = {}

        for name, table_ids in grouped.items():
            all_dfs = []
            for table_id in table_ids:
                try:
                    q = f"SELECT * FROM {table_id}"
                    df = syn.tableQuery(q).asDataFrame()
                    df["source_table"] = table_id  # track origin (optional)
                    all_dfs.append(df)
                except Exception as e:
                    print(f"Failed to fetch table {table_id}: {e}")
            if all_dfs:
                grouped_dataframes[name] = pd.concat(all_dfs, ignore_index=True)

        # Upload grouped dataframes to BigQuery
        for name, df in grouped_dataframes.items():
            out_table = f"bronze_METADATA_TABLE_Manifest_{name.replace(' ', '_').replace('-', '_')}"
            load_bq(
                client,
                htan_bq_project,
                medallion_layer,
                out_table,
                df,
            )

    # -----------------------
    # File ancestry walker → upstream IDs table
    # -----------------------
    bios = client.query("""
        SELECT * FROM `htan2-dcc.htan2_medallion_bronze.bronze_LINKING_VIEW_Biospecimen`
    """).result().to_dataframe()

    table_list = client.list_tables("htan2-dcc.htan2_medallion_bronze")

    all_columns = client.query("""
        SELECT table_name, column_name
        FROM `htan2-dcc.htan2_medallion_bronze.INFORMATION_SCHEMA.COLUMNS`
    """).result().to_dataframe()

    bq_schema = json.load(open("schema.json"))

    f = pd.DataFrame()

    for t in table_list:
        tn = t.table_id
        if tn not in ["OtherAssay", "ExSeqMinimal"] and "Auxiliary" not in tn and "Level" not in tn:
            continue

        print("\n Processing:", tn, "\n")

        cols = list(all_columns[all_columns["table_name"] == tn]["column_name"])

        common_cols = [
            "HTAN_Data_File_ID",
            "Filename",
            "entity_id",
            "Component",
            "project_name",
        ]
        if "HTAN_Parent_Biospecimen_ID" in cols:
            common_cols.append("HTAN_Parent_Biospecimen_ID")
        if "HTAN_Parent_Data_File_ID" in cols:
            common_cols.append("HTAN_Parent_Data_File_ID")

        qco = ", ".join(common_cols)
        df = client.query(f"""
            SELECT {qco}
            FROM `{t.project}.{t.dataset_id}.{t.table_id}`
        """).result().to_dataframe()

        f = pd.concat([f, df], ignore_index=True)

    # Expand comma/semicolon-separated parent lists into individual rows
    f = f.assign(HTAN_Parent_Data_File_ID=f.HTAN_Parent_Data_File_ID.str.split("[,;]")).explode("HTAN_Parent_Data_File_ID")
    f = f.assign(HTAN_Parent_Biospecimen_ID=f.HTAN_Parent_Biospecimen_ID.str.split("[,;]")).explode("HTAN_Parent_Biospecimen_ID")
    f = f.applymap(lambda x: x.strip() if isinstance(x, str) else x).drop_duplicates()

    print("\n Walking parent file ancestry \n")

    # Self-joins to walk parent → grandparent → great-grandparent
    f = (
        f.merge(
            f[["HTAN_Data_File_ID", "HTAN_Parent_Data_File_ID"]],
            left_on="HTAN_Parent_Data_File_ID",
            right_on="HTAN_Data_File_ID",
            how="left",
        )
        .drop_duplicates()
        .rename(columns={
            "HTAN_Parent_Data_File_ID_y": "gParent_File_ID",
            "HTAN_Parent_Data_File_ID_x": "HTAN_Parent_Data_File_ID",
            "HTAN_Data_File_ID_x": "HTAN_Data_File_ID",
        })
        .drop(columns="HTAN_Data_File_ID_y")
        .merge(
            f[["HTAN_Data_File_ID", "HTAN_Parent_Data_File_ID"]],
            left_on="gParent_File_ID",
            right_on="HTAN_Data_File_ID",
            how="left",
        )
        .drop_duplicates()
        .rename(columns={
            "HTAN_Data_File_ID_x": "HTAN_Data_File_ID",
            "HTAN_Parent_Data_File_ID_y": "ggParent_File_ID",
            "HTAN_Parent_Data_File_ID_x": "HTAN_Parent_Data_File_ID",
        })
        .drop(columns="HTAN_Data_File_ID_y")
    )

    # Coalesce 'highest' level parent data file
    f["coalesce"] = f[["ggParent_File_ID", "gParent_File_ID", "HTAN_Parent_Data_File_ID"]].bfill(axis=1).iloc[:, 0]

    # Map highest-available ancestor to its biospecimen
    f = (
        f.merge(
            f[["HTAN_Data_File_ID", "HTAN_Parent_Biospecimen_ID"]],
            left_on="coalesce",
            right_on="HTAN_Data_File_ID",
            how="left",
        )
        .drop_duplicates()
        .assign(HTAN_Parent_Biospecimen_ID_x=lambda x: x["HTAN_Parent_Biospecimen_ID_x"].fillna(x["HTAN_Parent_Biospecimen_ID_y"]))
        .rename(columns={
            "HTAN_Data_File_ID_x": "HTAN_Data_File_ID",
            "HTAN_Parent_Biospecimen_ID_x": "HTAN_Assayed_Biospecimen_ID",
        })
        .drop(columns=[
            "HTAN_Data_File_ID_y",
            "gParent_File_ID",
            "coalesce",
            "HTAN_Parent_Biospecimen_ID_y",
            "ggParent_File_ID",
        ])
    )

    # Join file table with biospecimen walker table
    id_prov = (
        f.merge(bios, on="HTAN_Assayed_Biospecimen_ID", how="left")
         .drop_duplicates()
         .rename(columns={"fileEntityId": "entityId"})
    )

    # Load upstream IDs
    load_bq(
        client,
        htan_bq_project,
        medallion_layer,
        "bronze_INDEXING_TABLE_Upstream_IDs",
        id_prov,
        bq_schema,
    )
    
    # -----------------------
    # Unique IDs (Datafile / Participant)
    # -----------------------
    unique_ids_minted_datafiles = (
        id_prov[["entity_id", "HTAN_Data_File_ID", "project_name"]]
        .drop_duplicates("HTAN_Data_File_ID")
        .dropna()
    )
    unique_ids_minted_patients = (
        id_prov[["entity_id", "HTAN_Participant_ID", "project_name"]]
        .drop_duplicates("HTAN_Participant_ID")
        .dropna()
    )

    load_bq(
        client,
        htan_bq_project,
        medallion_layer,
        "bronze_INDEXING_TABLE_Minted_Datafile_IDs",
        unique_ids_minted_datafiles,
    )
    load_bq(
        client,
        htan_bq_project,
        medallion_layer,
        "bronze_INDEXING_TABLE_Minted_Participant_IDs",
        unique_ids_minted_patients,
    )


if __name__ == "__main__":
    main()


